{% set version_match = load_file_regex(load_file="./nmrpy/version.py", regex_pattern="^__version__\s*=\s*'(.*)'") %}
{% set version = version_match[1] %}

package:
  name: nmrpy
  version: {{ version }}

source:
  path: ../..
  #url: https://pypi.io/packages/source/n/nmrpy/nmrpy-{{ version }}.tar.gz
  #sha256: 1f5a0030e1ec7399e4c6cc38cb64c23a89c631c43009485a3b36bd89caf247db
  #git_url: https://github.com/NMRPy/nmrpy.git
  #git_rev: 0.2.3

build:
  noarch: python
  number: 0
  include_recipe: True
  script: python -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - numpy
    - scipy
    - jupyterlab
    - matplotlib >=3.9.0
    - ipympl >=0.9.5
    - lmfit >=1.3.0
    - nmrglue >0.11
    - ipython >=8.0.0
    - python >=3.12
    - pydantic
    - pip
    - setuptools
    - wheel
  run:
    - numpy
    - scipy
    - jupyterlab
    - matplotlib >=3.9.0
    - ipympl >=0.9.5
    - lmfit >=1.3.0
    - nmrglue >0.11
    - ipython >=8.0.0
    - python >=3.12
    - pydantic

test:
  imports:
    - nmrpy
    - nmrpy.tests
  commands:
    - python -s -c "import nmrpy; nmrpy.test('noplot')"

about:
  home: "https://github.com/NMRPy/nmrpy"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt 
  summary: "A suite of tools for processing and analysing NMR spectra in Python."
  doc_url: https://nmrpy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jmrohwer
  maintainers:
    - Johann M. Rohwer
